movember_movember:
    resource: "@MovemberBundle/Resources/config/routing/movember.yml"
    prefix:   /

movember_homepage:
    path:     /
    defaults: { _controller: MovemberBundle:Default:index }
